<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" LogicalName="EasyOpenCore.Localization.%(Filename)%(Extension)" WithCulture="false" />
    <EmbeddedResource Include="Data\*.json" LogicalName="EasyOpenCore.Data.%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
